import React, {useEffect, useState} from 'react'
import {Link} from 'react-router-dom'
import {motion} from 'framer-motion'
import {ArrowRight, Instagram, MapPin, Menu, MessageCircle, Phone, Clock3, Dumbbell, Image as ImageIcon, LayoutDashboard, X, CheckCircle2, LogIn} from 'lucide-react'
import {supabase} from '../lib/supabase'
import '../styles.css'

const LOGO='/ds-fitness-logo.webp'
const contact1='918890311555', contact2='919214580585'
const maps='https://maps.app.goo.gl/AJGH8dacLCNuopdu5'
const instagram='https://www.instagram.com/dsfitnessbkn/'
const defaultPlans=[
 {name:'1 Month',price:1500,duration:'1 Month',category:'Gym'},
 {name:'3 Months',price:4000,duration:'3 Months',category:'Gym'},
 {name:'6 Months',price:7000,duration:'6 Months',category:'Gym'},
 {name:'Yearly',price:12000,duration:'12 Months',category:'Gym'},
 {name:'1 Month PT',price:6000,duration:'1 Month',category:'Personal Training'},
 {name:'3 Months PT',price:15000,duration:'3 Months',category:'Personal Training'}
]
const services=['Weight Training','Personal Training','Cardio','Zumba','Aerobics','Martial Arts','CrossFit','Diet Plans']
const facilities=['Imported Equipment','Changing Room','Air Conditioner','Locker','Security','Certified Trainer','Water Cooler','CCTV','Shower','Separate Ladies Batches']

function whatsapp(number,message){return `https://wa.me/${number}?text=${encodeURIComponent(message)}`}
function useReveal(){return {initial:{opacity:0,y:28},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.12},transition:{duration:.65,ease:'easeOut'}}}

function Logo({className=''}){return <img src={LOGO} alt="DS Fitness" className={`brand-logo ${className}`} loading="eager"/>}
function Header(){const [open,setOpen]=useState(false);return <header className="site-header"><div className="container nav"><Link to="/" onClick={()=>setOpen(false)} className="nav-logo"><Logo/></Link><nav className={open?'nav-links open':'nav-links'}><a href="#about" onClick={()=>setOpen(false)}>About</a><a href="#services" onClick={()=>setOpen(false)}>Services</a><a href="#plans" onClick={()=>setOpen(false)}>Plans</a><a href="#gallery" onClick={()=>setOpen(false)}>Gallery</a><a href="#contact" onClick={()=>setOpen(false)}>Contact</a><Link className="admin-link" to="/admin" onClick={()=>setOpen(false)}><LogIn size={15}/> Admin Login</Link></nav><button className="menu-btn" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></div></header>}
function WhatsAppFloat(){return <a className="wa-float" href={whatsapp(contact1,'Hello DS Fitness, I would like to know more about membership.')} target="_blank" rel="noreferrer"><MessageCircle/></a>}
export default function PublicSite(){const [plans,setPlans]=useState(defaultPlans);const [gallery,setGallery]=useState([]);useEffect(()=>{if(!supabase)return;supabase.from('membership_plans').select('*').eq('is_active',true).order('sort_order').then(({data})=>{if(data?.length)setPlans(data)});supabase.from('gallery').select('*').eq('is_active',true).order('sort_order').then(({data})=>{if(data)setGallery(data)})},[]);return <><Header/><main>
<section className="hero"><div className="hero-grid"></div><div className="container hero-inner"><motion.div {...useReveal()} className="hero-copy"><div className="eyebrow"><span></span> BIKANER'S FITNESS DESTINATION</div><div className="hero-logo-wrap"><Logo className="hero-logo"/></div><h1>Train harder.<br/><em>Live stronger.</em></h1><p>Serious training, premium equipment and expert guidance — built for people who refuse to stay ordinary.</p><div className="hero-actions"><a className="btn primary" href={whatsapp(contact1,'Hello DS Fitness, I want to enquire about membership.')}>Join / Enquire <ArrowRight size={18}/></a><a className="btn ghost" href="#plans">View Memberships</a></div><div className="hero-meta"><span><Clock3/> 5 AM–10 AM / 4 PM–10 PM</span><span><MapPin/> Bikaner, Rajasthan</span></div></motion.div></div><div className="hero-scroll">SCROLL <span></span></div></section>
<section id="about" className="section about"><div className="container split"><motion.div {...useReveal()}><div className="section-kicker">01 / THE GYM</div><h2>Built for <span>strength.</span><br/>Driven by discipline.</h2><p>DS Fitness is a focused training space in Bikaner led by Deepak Sharma, Certified Trainer. From strength and cardio to personal training and group disciplines, every session is designed around consistency and progress.</p><a className="text-link" href={whatsapp(contact1,'Hello DS Fitness, I want to visit the gym.')}>Talk to the gym <ArrowRight size={17}/></a></motion.div><motion.div {...useReveal()} className="about-card"><Dumbbell/><strong>Deepak Sharma</strong><span>Certified Trainer</span><div className="card-line"></div><small>Strength • Fitness • Performance</small></motion.div></div></section>
<section id="services" className="section dark"><div className="container"><motion.div {...useReveal()} className="section-head"><div><div className="section-kicker">02 / TRAINING</div><h2>Train your way.</h2></div><p>Multiple disciplines. One standard: serious training.</p></motion.div><div className="service-grid">{services.map((s,i)=><motion.div {...useReveal()} transition={{...useReveal().transition,delay:i*.04}} className="service-card" key={s}><span>0{i+1}</span><Dumbbell size={25}/><h3>{s}</h3><ArrowRight className="service-arrow" size={18}/></motion.div>)}</div></div></section>
<section className="section facilities"><div className="container"><motion.div {...useReveal()} className="section-head"><div><div className="section-kicker">03 / FACILITIES</div><h2>Everything you need<br/><span>to show up.</span></h2></div></motion.div><div className="facility-grid">{facilities.map((f,i)=><motion.div {...useReveal()} key={f} className="facility"><CheckCircle2 size={18}/><span>{f}</span></motion.div>)}</div></div></section>
<section id="plans" className="section plans dark"><div className="container"><motion.div {...useReveal()} className="section-head"><div><div className="section-kicker">04 / MEMBERSHIPS</div><h2>Choose your <span>commitment.</span></h2></div><p>Fees are non-refundable & non-adjustable.</p></motion.div><div className="plan-grid">{plans.map((p,i)=><motion.div {...useReveal()} className={`plan-card ${i===3?'featured':''}`} key={p.id||p.name}><div className="plan-tag">{p.category}</div><h3>{p.name}</h3><div className="price">₹{Number(p.price).toLocaleString('en-IN')}<small> / {p.duration}</small></div><a className="btn small primary" href={whatsapp(contact1,`Hello DS Fitness, I want details about the ${p.name} plan (₹${p.price}).`)}>Enquire <ArrowRight size={15}/></a></motion.div>)}</div></div></section>
<section className="section pt"><div className="container pt-banner"><div><div className="section-kicker">05 / PERSONAL TRAINING</div><h2>More focus.<br/><span>More progress.</span></h2><p>Personal training for members who want structured attention, technique and accountability.</p></div><a className="btn primary" href={whatsapp(contact2,'Hello DS Fitness, I am interested in Personal Training.')}>Ask about PT <ArrowRight size={18}/></a></div></section>
<section id="gallery" className="section dark"><div className="container"><motion.div {...useReveal()} className="section-head"><div><div className="section-kicker">06 / GALLERY</div><h2>Inside <span>DS Fitness.</span></h2></div><p>Real training. Real atmosphere. Your next session starts here.</p></motion.div>{gallery.length?<div className="gallery-grid">{gallery.map(g=><img key={g.id} src={g.image_url} alt={g.title||'DS Fitness'} loading="lazy"/>)}</div>:<div className="gallery-empty"><ImageIcon size={30}/><p>Gym gallery coming soon.</p><span>More real DS Fitness moments will appear here.</span></div>}</div></section>
<section id="contact" className="section contact"><div className="container contact-grid"><motion.div {...useReveal()}><div className="section-kicker">07 / FIND US</div><h2>Ready to <span>train?</span></h2><p>DS FITNESS<br/>Tirtham Circle, Near Union Bank<br/>Hanuman Hatha, Bikaner City<br/>Rajasthan - 334001</p><div className="contact-actions"><a className="btn primary" href={maps} target="_blank" rel="noreferrer"><MapPin size={18}/> Get Directions</a><a className="btn ghost" href={instagram} target="_blank" rel="noreferrer"><Instagram size={18}/> Instagram</a></div></motion.div><motion.div {...useReveal()} className="contact-box"><div><Clock3/><strong>Open daily</strong><span>5:00 AM – 10:00 AM</span><span>4:00 PM – 10:00 PM</span></div><div><Phone/><strong>WhatsApp</strong><a href={whatsapp(contact1,'Hello DS Fitness, I have an enquiry.')}>+91 88903 11555</a><a href={whatsapp(contact2,'Hello DS Fitness, I have an enquiry.')}>+91 92145 80585</a></div></motion.div></div></section>
</main><footer className="footer"><div className="container footer-inner"><Logo/><span>© {new Date().getFullYear()} DS FITNESS. Train. Progress. Repeat.</span><Link to="/admin"><LayoutDashboard size={16}/> Admin</Link></div></footer><WhatsAppFloat/></>}
